POST http://localhost:3001/api/login
content-type: application/json

{
  "username": "ajurisic",
  "pass": "tajna"
}

//TOKEN
# "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqdXJpc2ljIiwiaWQiOiI1ZjljMjM1OGYxZjExYzI5ZjgzNTA1YTYiLCJpYXQiOjE2MDQwNzI2NzJ9.4DpSyqJS3E_BPbvuvzJNAmMzDxkLkAVF5F4ALJJRvNg"